// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbkXmD9ql3lHsa8s7bFgNb2-lbzoFtFZM',
    appId: '1:964697908697:web:0b83885d258c34bb6b25c8',
    messagingSenderId: '964697908697',
    projectId: 'bitezz-fcaf0',
    authDomain: 'bitezz-fcaf0.firebaseapp.com',
    storageBucket: 'bitezz-fcaf0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVQ6geX9gv8TTX-PzJKUY1ykSrnbdM030',
    appId: '1:964697908697:android:da7532937b506daf6b25c8',
    messagingSenderId: '964697908697',
    projectId: 'bitezz-fcaf0',
    storageBucket: 'bitezz-fcaf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCR21QB4wov0ywJqZYSpPaGyIVCjeTx6c',
    appId: '1:964697908697:ios:14727907119e419f6b25c8',
    messagingSenderId: '964697908697',
    projectId: 'bitezz-fcaf0',
    storageBucket: 'bitezz-fcaf0.firebasestorage.app',
    iosBundleId: 'com.example.bitez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCR21QB4wov0ywJqZYSpPaGyIVCjeTx6c',
    appId: '1:964697908697:ios:14727907119e419f6b25c8',
    messagingSenderId: '964697908697',
    projectId: 'bitezz-fcaf0',
    storageBucket: 'bitezz-fcaf0.firebasestorage.app',
    iosBundleId: 'com.example.bitez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbkXmD9ql3lHsa8s7bFgNb2-lbzoFtFZM',
    appId: '1:964697908697:web:de6c99d8fb8200396b25c8',
    messagingSenderId: '964697908697',
    projectId: 'bitezz-fcaf0',
    authDomain: 'bitezz-fcaf0.firebaseapp.com',
    storageBucket: 'bitezz-fcaf0.firebasestorage.app',
  );
}
